### ISSUE TITLE
REQUEST: New membership for 1037827920

### ISSUE THREAD

**Issue by 1037827920** [DragonOS-Community/teams_data#15]
### GitHub Username

@1037827920

### DragonOS Account的ID（在 https://account.dragonos.org.cn/login/DragonOS 右上角“我的账户”中获取）

@1037827920

### Organization you are requesting membership in

DragonOS-Community

### 推荐者1

@fslongjin

### 推荐者2

@Samuka007 

### 在此一一列出你对DragonOS项目的贡献。 List of contributions to the DragonOS project

- PRs authored: 
   [[Patch fix clippy 0315evening ](https://github.com/DragonOS-Community/DragonOS/pull/609)](https://github.com/DragonOS-Community/DragonOS/pull/609)
    [[fix: mkdir输出错误信息; feat: 实现get_pathname ](https://github.com/DragonOS-Community/DragonOS/pull/615)](https://github.com/DragonOS-Community/DragonOS/pull/615)
    [[Patch fix clippy](https://github.com/DragonOS-Community/DragonOS/pull/629)](https://github.com/DragonOS-Community/DragonOS/pull/629)
    [[Patch feat robust futex](https://github.com/DragonOS-Community/DragonOS/pull/682)](https://github.com/DragonOS-Community/DragonOS/pull/682)
    [[feat(driver/acpi_pm): Implement ACPI PM Timer](https://github.com/DragonOS-Community/DragonOS/pull/772)](https://github.com/DragonOS-Community/DragonOS/pull/772)
    [[feat(driver/pci): 完善pci root结构体，增加portio的pci配置空间访问](https://github.com/DragonOS-Community/DragonOS/pull/818)](https://github.com/DragonOS-Community/DragonOS/pull/818)
    [[fix(time): modify update wall time](https://github.com/DragonOS-Community/DragonOS/pull/836)](https://github.com/DragonOS-Community/DragonOS/pull/836)
    [[fix: 错误处理 ; ' " 导致的崩溃](https://github.com/DragonOS-Community/NovaShell/pull/23)](https://github.com/DragonOS-Community/NovaShell/pull/23)
    [[fix: 输出多余的光标和命令信息 ](https://github.com/DragonOS-Community/NovaShell/pull/25)](https://github.com/DragonOS-Community/NovaShell/pull/25)
    [[fix: rmdir没有找到目录时不打印日志](https://github.com/DragonOS-Community/NovaShell/pull/30)](https://github.com/DragonOS-Community/NovaShell/pull/30)
 - SIG projects I am involved with:
   SIG-cloud provider 
    [[关于SIG-Cloud Provider类别](https://bbs.dragonos.org.cn/t/topic/243)](https://bbs.dragonos.org.cn/t/topic/243)
    [[移植到CVM进入第一个内核线程后发生panic](https://bbs.dragonos.org.cn/t/topic/256)](https://bbs.dragonos.org.cn/t/topic/256)

**Comment by fslongjin** [comment]
需要修改issue名字

**Comment by Samuka007** [comment]
如果没有问题，我将关闭此Issue并将 @1037827920 加入组织中。

**Comment by fslongjin** [comment]
无问题，赞成
